

version: "3.9"

services:
  mongodb:
    image: mongo:6.0
    container_name: hackathon-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: db
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: